"""Drop salt column from User

Revision ID: 6bb6727c9e9e
Revises: 0c238cf124e0
Create Date: 2023-03-27 16:36:16.622025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bb6727c9e9e'
down_revision = '0c238cf124e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_salt_key', 'user', type_='unique')
    op.drop_column('user', 'salt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('salt', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_salt_key', 'user', ['salt'])
    # ### end Alembic commands ###
